version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend-api-db
      MYSQL_USER: backend-api-user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend_api:
    build:
      context: ./backend-api
    container_name: backend-api-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql
    restart: on-failure:5

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend_api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
